/* ═══════════════════════════════════════════════════════════════════
   REVISION SKILLS

   A skill is the smallest thing a child would say "I need to revise this"
   about — "Rotating a shape about a point", not "Geometry". Each one names
   the question templates that test it, so its practice questions come
   straight out of the existing bank; nothing new has to be written.

   Fields:
     id        stable key, used by the mastery store
     topic     the topic tile it sits under
     title     what the child sees
     idea      one or two sentences: what this actually is
     templates the generators that test it (see q.template)

   The "how to do it" line, the worked example and any diagram are taken
   from a real question at run time — the method is already attached to
   every question as q.explain, so the card and the practice cannot drift
   apart.

   Every template in the maths bank belongs to exactly one skill; the
   revision screen checks this on load and reports anything orphaned.
═══════════════════════════════════════════════════════════════════ */
(() => {
  const root = typeof window !== "undefined" ? window : globalThis;

  root.SKILLS = [
    /* ── Numbers ── */
    { id: "num-place-value", topic: "Numbers", title: "Place value",
      idea: "What a digit is worth depends on the column it sits in. The 7 in 7,240 is worth seven thousand, not seven.",
      concepts: ["place-value-rounding"],
      templates: ["numPlaceValue", "numPlaceValueDiff", "numWordsToDigits"] },
    { id: "num-rounding", topic: "Numbers", title: "Rounding",
      idea: "Replacing a number with a nearby, tidier one. You look at the digit just after the place you are rounding to, and nothing else.",
      concepts: ["place-value-rounding"],
      templates: ["numRounding", "numRoundLargePlace", "numRoundingBounds"] },
    { id: "num-primes-factors", topic: "Numbers", title: "Primes and factors",
      idea: "A factor divides into a number exactly. A prime has only two factors: 1 and itself.",
      concepts: ["factors-multiples-primes"],
      templates: ["numIsPrime", "numFactorCount", "numPrimeFactorCount", "numPrimeSumSquare", "numSquaresMinusCubes", "numFactorStatements"] },
    { id: "num-lcm-hcf", topic: "Numbers", title: "LCM and HCF",
      idea: "The lowest common multiple is the first number both go into. The highest common factor is the biggest number that goes into both.",
      concepts: ["factors-multiples-primes"],
      templates: ["numLCM", "numHCF", "numHCFofFour", "numBusLCM", "numRemainderPuzzle"] },
    { id: "num-powers", topic: "Numbers", title: "Powers and roots",
      idea: "A small raised number tells you how many times to multiply a number by itself. 9² means 9 × 9, not 9 × 2.",
      concepts: ["factors-multiples-primes"],
      templates: ["numPowers", "numCubeMissing", "numLastDigitPower"] },
    { id: "num-calculating", topic: "Numbers", title: "Written calculation",
      idea: "Adding, subtracting, multiplying and dividing larger numbers on paper, keeping the columns lined up.",
      concepts: ["place-value-rounding"],
      templates: ["numArithmetic", "numWordProblem"] },
    { id: "num-puzzles", topic: "Numbers", title: "Number puzzles",
      idea: "Questions where you have to search or reason rather than follow one procedure — building numbers from digits, or comparing several calculations.",
      concepts: ["comparing-ordering-numbers"],
      templates: ["numSmallestEvenFromDigits", "numFourConsecOdd", "numCompareExpressions",
                  "numDigitProductCount", "numClosestToTarget"] },

    /* ── Decimals ── */
    { id: "dec-four-rules", topic: "Decimals", title: "Adding and subtracting decimals",
      idea: "The decimal points must line up underneath each other. Fill any gaps with zeros so both numbers have the same length.",
      concepts: ["adding-subtracting-decimals"],
      templates: ["decAdd", "decSubtract"] },
    { id: "dec-multiply-divide", topic: "Decimals", title: "Multiplying and dividing decimals",
      idea: "Multiply as if there were no decimal point, then put it back. Dividing by a number below 1 makes the answer bigger.",
      concepts: ["multiplying-dividing-decimals"],
      templates: ["decMultiply", "decDivide", "decDivideByDecimal", "decChainedOf", "decMultiplyBySmall", "decMultiplyGivenFact"] },
    { id: "dec-compare-round", topic: "Decimals", title: "Comparing and rounding decimals",
      idea: "Compare place by place from the left. More digits does not mean a bigger number: 0.093 is smaller than 0.39.",
      concepts: ["comparing-ordering-decimals"],
      templates: ["decCompare", "decRound", "decHalfway", "decOrderMixed"] },
    { id: "dec-convert", topic: "Decimals", title: "Decimals into fractions",
      idea: "The digits after the point sit over 10, 100 or 1000 depending on how many there are, then cancel down.",
      concepts: ["decimal-place-value"],
      templates: ["decToFrac"] },
    { id: "dec-reasoning", warmUp: "dec-multiply-divide", topic: "Decimals", title: "Using a fact you are given",
      idea: "Some questions hand you an answer and ask a related one. Adjust by powers of ten instead of starting again.",
      concepts: ["multiplying-dividing-decimals"],
      templates: ["decMultFactReuse", "decPriceChange", "decUnitPrice", "decMoneySplit"] },

    /* ── Fractions ── */
    { id: "frac-add-subtract", topic: "Fractions", title: "Adding and subtracting fractions",
      idea: "You can only add or subtract fractions once the bottoms match. Change the denominators first, then work on the tops alone.",
      concepts: ["fractions-of-amounts-simple-calculations"],
      templates: ["fracAdd", "fracSubtract"] },
    { id: "frac-multiply-divide", topic: "Fractions", title: "Multiplying and dividing fractions",
      idea: "Multiply straight across. To divide, turn the second fraction upside down and multiply instead.",
      concepts: ["fractions-of-amounts-simple-calculations"],
      templates: ["fracMultiply", "fracDivide", "fracMixedMultiply"] },
    { id: "frac-simplify", topic: "Fractions", title: "Simplifying and mixed numbers",
      idea: "Cancel the top and bottom by the same number. An improper fraction can be split into whole ones plus a remainder.",
      concepts: ["equivalent-simplifying-fractions", "comparing-ordering-fractions"],
      templates: ["fracSimplify", "fracImproperToMixed", "fracBetweenTwo"] },
    { id: "frac-of-amount", topic: "Fractions", title: "A fraction of an amount",
      idea: "'Of' means multiply. Divide by the bottom to find one part, then multiply by the top.",
      concepts: ["understanding-fractions"],
      templates: ["fracOfX", "fracOfFrac", "figShadedFraction", "figShadedTriangles"] },
    { id: "frac-remainder", warmUp: "frac-of-amount", topic: "Fractions", title: "Fractions of what is left",
      idea: "When a second fraction is taken, it is usually a fraction of the remainder, not of the original amount. These often have to be worked backwards.",
      concepts: ["fractions-of-amounts-simple-calculations"],
      templates: ["fracReverseTwoStage", "fracOfRemainderMoney", "fracOfCapacity"] },

    /* ── Percentages ── */
    { id: "pct-basics", topic: "Percentages", title: "Finding a percentage",
      idea: "Per cent means 'out of 100'. Find 10% by dividing by 10, or 1% by dividing by 100, then build what you need.",
      concepts: ["what-percent-means", "fractions-decimals-percentages"],
      templates: ["pctOf", "pctFracToPct", "pctDecToPct"] },
    { id: "pct-change", topic: "Percentages", title: "Increases, discounts and interest",
      idea: "Work out the change and add or subtract it — or go straight to what is left: 30% off means paying 70%.",
      concepts: ["percentage-change"],
      templates: ["pctSalePrice", "pctIncrease", "pctSimpleInterest", "pctSaleChange"] },
    { id: "pct-reverse", topic: "Percentages", title: "Working back to the whole",
      idea: "You are told what a percentage is worth and asked for 100%. Scale back up rather than taking a percentage again.",
      concepts: ["finding-percentages-of-amounts"],
      templates: ["pctReverse"] },
    { id: "pct-chained", warmUp: "pct-basics", topic: "Percentages", title: "Percentages one after another",
      idea: "Two percentage changes cannot be added together. Each one applies to the answer before it.",
      concepts: ["percentage-change"],
      templates: ["pctChained", "pctProfitAfterLoss", "pctProfitPerItem"] },
    { id: "pct-sets", warmUp: "pct-basics", topic: "Percentages", title: "Overlapping groups",
      idea: "When people belong to two groups at once, adding the groups counts the overlap twice. Subtract it once to fix that.",
      concepts: ["finding-percentages-of-amounts"],
      templates: ["pctVennNeither"] },

    /* ── BIDMAS ── */
    { id: "bid-order", topic: "BIDMAS", title: "Order of operations",
      idea: "Brackets, Indices, Divide and Multiply, then Add and Subtract — and left to right within each pair.",
      concepts: ["the-order-of-operations", "multiply-divide-in-the-middle"],
      templates: ["bidSimple", "bidBrackets", "bidPowers", "bidMixed", "bidFractionBar", "bidRootsAndPowers", "bidNotEqual"] },
    { id: "bid-negatives", topic: "BIDMAS", title: "Negative numbers",
      idea: "Two negatives multiplied give a positive. Counting across zero is easiest in two hops: up to zero, then on past it.",
      concepts: ["indices-negatives-careful-signs", "Numbers/negative-numbers-number-lines"],
      templates: ["bidNegative", "bidTempChange", "bidNegativePower"] },
    { id: "bid-puzzles", warmUp: "bid-order", topic: "BIDMAS", title: "Missing brackets and operations",
      idea: "You are given the answer and asked what makes it true. Try each possibility, remembering that × and ÷ happen before + and −.",
      concepts: ["brackets-first"],
      templates: ["bidNestedBrackets", "bidMissingOperator", "bidInsertBrackets", "bidBracketsFourTerms"] },

    /* ── Algebra ── */
    { id: "alg-substitute", topic: "Algebra", title: "Substituting into a formula",
      idea: "Replace each letter with its value, then work the arithmetic out in the usual order. Watch the signs.",
      concepts: ["substitution", "function-machines"],
      templates: ["algSubLinear", "algSubMulti", "algSubQuadratic", "algCustomOp", "algFunctionMachine"] },
    { id: "alg-solve", topic: "Algebra", title: "Solving equations",
      idea: "Get the letter on its own by doing the same thing to both sides, undoing the operations in reverse order.",
      concepts: ["equations"],
      templates: ["algSolve1Step", "algSolve2Step", "algSolveBothSides", "algChainSubstitute", "algPowerEquation", "algRemainderDivisor", "algInequalityInteger"] },
    { id: "alg-simplify", topic: "Algebra", title: "Collecting like terms",
      idea: "Only terms with the same letter can be added together. The a terms and the b terms stay separate.",
      concepts: ["expressions", "factorising-expansion"],
      templates: ["algSimplifyTerms", "algExpressionChange"] },
    { id: "alg-word-problems", warmUp: "alg-solve", topic: "Algebra", title: "Turning words into equations",
      idea: "The hard part is writing the equation, not solving it. Name the unknown, then translate each sentence into maths.",
      concepts: ["equations", "magic-squares"],
      templates: ["algWeightPair", "algTriangleAngles", "algThreeItemPricing", "algSimultaneous"] },

    /* ── Sequences ── */
    { id: "seq-continue", topic: "Sequences", title: "Continuing a sequence",
      idea: "Find what happens from one term to the next — added, multiplied, or built from the two before — then carry it on.",
      concepts: ["spotting-the-rule", "arithmetic-sequences"],
      templates: ["seqArithNext", "seqFibLike", "seqGeomNext", "seqBallPattern", "seqFibMissingStart", "seqRecurrenceMissing", "seqInterleaved"] },
    { id: "seq-nth-term", topic: "Sequences", title: "The nth term",
      idea: "A rule that jumps straight to any term without writing out the others. The number in front of n is the common difference.",
      concepts: ["position-rules"],
      templates: ["seqArithNth", "seqArithNthFormula", "seqMatchstickNth", "seqNthFromTwoTerms", "seqQuadraticNth", "seqWhichTerm"] },
    { id: "seq-changing-gaps", warmUp: "seq-continue", topic: "Sequences", title: "Sequences with changing gaps",
      idea: "When the differences are not constant, look at the differences between the differences. That second pattern is usually steady.",
      concepts: ["missing-terms-pattern-problems"],
      templates: ["seqQuadraticNext", "seqQuadraticDecreasing", "seqTriangular", "seqArithSum"] },

    /* ── Ratio ── */
    { id: "rat-simplify-share", topic: "Ratio", title: "Simplifying and sharing in a ratio",
      idea: "Add the parts to find how many shares there are, work out what one share is worth, then multiply up.",
      concepts: ["writing-simplifying-ratios", "sharing-in-a-ratio"],
      templates: ["ratSimplify", "ratSplit", "ratWordTotal", "ratDifference", "ratThreePart", "ratFractionOfWhole"] },
    { id: "rat-proportion", topic: "Ratio", title: "Proportion and recipes",
      idea: "Scale everything by the same factor. Finding the amount for one first often makes the numbers easier.",
      concepts: ["proportion-problems"],
      templates: ["ratRecipe", "ratInverseProp", "ratThreeCategories", "ratInverseTime", "ratBestValue", "ratEqualise"] },
    { id: "rat-scale", topic: "Ratio", title: "Map scales",
      idea: "The scale tells you what one centimetre stands for. Multiply to get the real distance, divide to get back to the map.",
      concepts: ["equivalent-ratios-scaling"],
      templates: ["ratMapScale", "ratMapReverse"] },
    { id: "rat-linking", warmUp: "rat-simplify-share", topic: "Ratio", title: "Linking two ratios",
      idea: "Two ratios sharing a quantity can be joined by scaling them until that shared number matches in both.",
      concepts: ["equivalent-ratios-scaling"],
      templates: ["ratChained", "ratAfterChange", "ratCompareTwoRatios"] },

    /* ── Speed ── */
    { id: "spd-formula", topic: "Speed", title: "Speed, distance and time",
      idea: "Speed is distance divided by time. Cover the one you want and the formula tells you what to do with the other two.",
      concepts: ["speed-distance-time-basics", "matching-units"],
      templates: ["spdFindSpeed", "spdFindDistance", "spdFindTime", "spdMphHoursMin", "spdSpeedFromMinutes"] },
    { id: "spd-two-travellers", warmUp: "spd-formula", topic: "Speed", title: "Two things moving at once",
      idea: "Work out where each one is at the same moment. Travelling towards each other, the gap closes at both speeds added together.",
      concepts: ["finding-time-in-journeys"],
      templates: ["spdGapBetweenTwo", "spdCatchUp", "spdMeetingPoint"] },
    { id: "spd-average", warmUp: "spd-formula", topic: "Speed", title: "Average speed",
      idea: "Average speed is the whole distance divided by the whole time. It is almost never the average of the two speeds.",
      concepts: ["average-speed-problems"],
      templates: ["spdAverageTwoLegs"] },
    { id: "spd-graphs", topic: "Speed", title: "Reading a distance-time graph",
      idea: "The steepness of the line is the speed. A flat line means the distance is not changing, so the journey has stopped.",
      concepts: ["speed-distance-time-basics"],
      templates: ["figDistanceTimeStationary", "figDistanceTimeSpeed", "figTwoTravellersGraph"] },

    /* ── Measurement ── */
    { id: "mea-units", topic: "Measurement", title: "Converting units",
      idea: "Decide whether the new unit is bigger or smaller than the old one, then multiply or divide by the right power of ten.",
      concepts: ["converting-units", "choosing-units-estimating"],
      templates: ["meaUnitConvert", "meaInchConvert", "meaTempDiff", "meaPourFromContainer", "meaEstimateWeight"] },
    { id: "mea-area-perimeter", topic: "Measurement", title: "Area and perimeter",
      idea: "Perimeter is the distance all the way round. Area is the space inside. Add for one, multiply for the other.",
      concepts: ["perimeter-area"],
      templates: ["meaAreaPerim", "meaSquaresInRectangle", "figCompoundPerimeter"] },
    { id: "mea-volume", topic: "Measurement", title: "Volume and surface area",
      idea: "Volume is how much fits inside; surface area is the skin around it. For a prism, find the end face first, then multiply by the length.",
      concepts: ["perimeter-area"],
      templates: ["meaVolumeCube", "meaCompoundVolume", "meaSurfaceAreaFromVolume"] },
    { id: "mea-money", topic: "Measurement", title: "Money problems",
      idea: "Work everything into the same units, add up what is spent, then subtract from what was handed over.",
      concepts: ["reading-scales-timetables"],
      templates: ["meaMoneyChange", "numMultiItemTotal"] },
    { id: "mea-scaling", warmUp: "mea-area-perimeter", topic: "Measurement", title: "Scaling, overlaps and folding",
      idea: "Lengths and areas do not scale the same way: double the lengths and the area goes up four times.",
      concepts: ["perimeter-area"],
      templates: ["meaOverlapArea", "meaScaleArea", "meaFoldPaper", "meaFrameWidth"] },

    /* ── Geometry ── */
    { id: "geo-angle-facts", topic: "Geometry", title: "Angle facts",
      idea: "Angles on a straight line add to 180°, angles around a point to 360°, and angles in a triangle to 180°.",
      concepts: ["angle-facts", "parallel-lines-special-angles"],
      templates: ["geoAngleSum", "geoAngleType", "geoComplementary", "figAnglesOnLine", "figAnglesAtPoint"] },
    { id: "geo-polygons", topic: "Geometry", title: "Angles in polygons",
      idea: "The interior angles of a shape with n sides add to (n − 2) × 180°. For a regular shape, divide that by n for one angle.",
      concepts: ["angle-facts"],
      templates: ["geoShapeAngle", "geoPolygonFromAngleSum", "geoPolygonMissingAngle"] },
    { id: "geo-shape-properties", topic: "Geometry", title: "Properties of shapes",
      idea: "Each shape has its own set of facts: equal sides, parallel sides, right angles. Questions often ask which fact does not hold.",
      concepts: ["shape-properties"],
      templates: ["geoShapeProperty", "geoShapeSplit", "geoPrismFEV", "geoTriangleInequality", "geoNameTriangles", "geoSplitPolygon"] },
    { id: "geo-symmetry", topic: "Geometry", title: "Symmetry",
      idea: "A line of symmetry folds a shape exactly onto itself. Rotational order counts how many times it looks the same in one full turn.",
      concepts: ["symmetry-coordinates-movement"],
      templates: ["geoLinesSymmetry", "geoRotSymmetry", "geoSymmetryCombined", "geoSymmetryLetters", "geoShapeFromSymmetry"] },
    { id: "geo-area", topic: "Geometry", title: "Area of triangles and cut-out shapes",
      idea: "A triangle is base × height ÷ 2 — the halving is the step people forget. For a shape with a piece removed, subtract.",
      concepts: ["shape-properties"],
      templates: ["geoTriangleArea", "geoShadedArea", "geoCuboidMissingEdge"] },
    { id: "geo-coordinates", topic: "Geometry", title: "Coordinates",
      idea: "Read across first, then up: x before y. The midpoint of a line is the average of the two x values and of the two y values.",
      concepts: ["symmetry-coordinates-movement"],
      templates: ["figCoordinatesRead", "figCoordinatesMidpoint", "geoParallelogramVertex"] },
    { id: "geo-compass", topic: "Geometry", title: "Compass directions and turns",
      idea: "The eight compass points sit 45° apart, so one right angle is two points round. Turning is counting points, not guessing.",
      concepts: ["symmetry-coordinates-movement"],
      templates: ["geoCompassTurn", "geoCompassAngle"] },
    { id: "geo-rotation", warmUp: "geo-coordinates", topic: "Geometry", title: "Rotating a shape about a point",
      idea: "Turning a shape around a fixed point. The point can be anywhere on the grid — it does not have to be the corner.",
      concepts: ["symmetry-coordinates-movement"],
      templates: ["geoRotationCoords", "geoTransformCompose"] },

    /* ── Statistics ── */
    { id: "stat-averages", topic: "Statistics", title: "Mean, median, mode and range",
      idea: "Mean is the total shared out. Median is the middle once sorted. Mode is the most common. Range is largest minus smallest.",
      concepts: ["mean-median-mode-range"],
      templates: ["statMean", "statMedian", "statMode", "statRange", "statMeanOfFactors", "statMedianAngleTriangle"] },
    { id: "stat-averages-backwards", warmUp: "stat-averages", topic: "Statistics", title: "Working backwards from an average",
      idea: "If you know the mean and how many there are, you know the total. That total is the way in to a missing value.",
      concepts: ["mean-median-mode-range"],
      templates: ["statMissingMean", "statCombinedMean"] },
    { id: "stat-tables", topic: "Statistics", title: "Frequency tables",
      idea: "A frequency table counts how many times each value happened. Multiply value by frequency to get totals, never just add the frequencies.",
      concepts: ["pictograms-frequency-tables"],
      templates: ["statFreqMidpoint", "statFreqTotal", "statMedianFromFreq"] },
    { id: "stat-charts", topic: "Statistics", title: "Reading charts",
      idea: "Always check the scale or the key before reading anything off — one square or one symbol is often worth more than one.",
      concepts: ["reading-tables-charts"],
      templates: ["statPictogram", "figBarChartTotal", "figBarChartDifference", "figPictogram", "statCorrelation", "figBarChartMode"] },
    { id: "stat-pie", topic: "Statistics", title: "Pie charts",
      idea: "A full circle is 360°, so each degree stands for the same number of people. Find that, then scale to the sector you need.",
      concepts: ["reading-tables-charts"],
      templates: ["statPieAngle", "statPieFromAngle", "figPieChart"] },
    { id: "stat-venn", warmUp: "stat-charts", topic: "Statistics", title: "Venn diagrams",
      idea: "The overlap belongs to both groups at once. 'Only football' means the left part alone; 'football' means the left part plus the overlap.",
      concepts: ["comparing-data"],
      templates: ["figVennOnly"] },

    /* ── Probability ── */
    { id: "prob-basics", topic: "Probability", title: "Simple probability",
      idea: "The number of ways you want, over the total number of ways. The chance of something not happening is 1 minus the chance it does.",
      concepts: ["probability-scale", "equally-likely-outcomes", "probability-in-different-forms"],
      templates: ["probBagPick", "probDie", "probCoin", "probComplement", "probExpected", "probTwoWayTable"] },
    { id: "prob-combined", warmUp: "prob-basics", topic: "Probability", title: "Two events together",
      idea: "For both to happen, multiply the two chances. If nothing is put back, the total shrinks for the second pick.",
      concepts: ["combined-outcomes-simple-tables"],
      templates: ["probIndependent", "probWithoutReplacement", "probTwoDiceSum", "probAtLeastOne", "probTwoSpinnersSum"] },

    { id: "prob-two-picks", warmUp: "prob-basics", topic: "Probability",
      title: "Two or three picks from the same bag",
      idea: "With nothing put back the bag changes between picks: one fewer of that colour on top and one fewer counter altogether underneath.",
      concepts: ["combined-outcomes-simple-tables"],
      templates: ["probTwoSameColour", "probOneOfEach", "probConditionalSecond",
                  "probThreeDrawsAllSame"] },
    { id: "prob-complement", warmUp: "prob-basics", topic: "Probability",
      title: "Working backwards from 'not'",
      idea: "'At least one' and 'not all the same' are far quicker upside down: find the chance of the thing you do not want, then take it from 1.",
      concepts: ["combined-outcomes-simple-tables"],
      templates: ["probNotAllSame", "probAtLeastOneSix"] },
    { id: "prob-reasoning", warmUp: "prob-basics", topic: "Probability",
      title: "Finding what is missing",
      idea: "Some questions give you the probability and ask for the numbers behind it. Write the probability as a fraction of the counts, then solve.",
      concepts: ["combined-outcomes-simple-tables"],
      templates: ["probFindOtherIndependent", "probAddToTarget"] },

    /* ── Logic ── */
    { id: "log-consecutive", topic: "Logic", title: "Consecutive numbers",
      idea: "Numbers in a run share a middle. Divide the total by how many there are to find it, then step out either side.",
      concepts: ["consecutive-numbers-and-means", "ordering-and-ranking-problems"],
      templates: ["logConsecutiveIntSum", "logConsecutiveEvenSum", "logConsecutiveOddPuzzle", "logSumAndDiff"] },
    { id: "log-palindromes", topic: "Logic", title: "Palindromes",
      idea: "A palindrome reads the same both ways. Fix the front digits and mirror them rather than testing every number.",
      concepts: ["palindromic-number-logic", "pattern-and-rule-logic"],
      templates: ["logPalindromeYesNo", "logNextPalindrome", "logSquarePalindromesInRange"] },
    { id: "log-calendar", topic: "Logic", title: "Days, dates and leap years",
      idea: "Days repeat every 7, so only the remainder matters. A date moves on one day each year, or two across a leap year.",
      concepts: ["calendar-and-odd-day-reasoning", "reading-clues-carefully"],
      templates: ["logDayOfWeek", "logDayWeeksAgo", "logDayShiftAcrossYear", "logLeapYearPick", "logLeapBirthday"] },
    { id: "log-clocks", warmUp: "log-calendar", topic: "Logic", title: "Clocks and time zones",
      idea: "The minute hand moves 6° a minute and the hour hand 0.5°, so the hour hand drifts past the hour as the minutes pass.",
      concepts: ["clock-angles-and-mirror-times"],
      templates: ["logClockAngleAtHour", "logClockMirror", "logTimeZone", "logClockReflexAngle"] },
    { id: "log-grids", topic: "Logic", title: "Number grids and pyramids",
      idea: "Every row, side or block follows one rule. Find a line where you know almost everything and start there.",
      concepts: ["magic-squares-pyramids-and-arithmagons", "letter-number-codes", "elimination-tables"],
      templates: ["logArithmagonProduct", "logAdditionPyramid", "logMagicSquareRow", "logLetterPuzzle", "logDigitSumOfSum"] },

    /* ── Counting Principle ── */
    { id: "count-stages", topic: "Counting Principle", title: "Multiplying the choices",
      idea: "When one choice is followed by another, multiply the numbers of options. Add only when the choices are alternatives rather than stages.",
      concepts: ["stages-and-multiplication"],
      templates: ["countStages", "countPlateLettersDigits"] },
    { id: "count-order-matters", warmUp: "count-stages", topic: "Counting Principle",
      title: "Arrangements where order matters",
      idea: "When nothing may be reused, the choices shrink by one at every place: 6 x 5 x 4. A rule such as 'must be even' or 'cannot start with 0' fixes that place first.",
      concepts: ["restrictions-and-rules"],
      templates: ["countArrangeNoRepeat", "countArrangeFirstRestrict",
                  "countEvenNoRepeat", "countGreaterThan"] },
    { id: "count-choosing", warmUp: "count-stages", topic: "Counting Principle",
      title: "Choosing a group, where order does not matter",
      idea: "A team of 3 from 8 is not 8 x 7 x 6: that counts every team once for each order it could be picked in. Divide by the arrangements of the group itself.",
      concepts: ["worded-counting-problems"],
      templates: ["countChooseCommittee", "countHandshakes", "countGridPaths"] },
    { id: "count-identical", warmUp: "count-order-matters", topic: "Counting Principle",
      title: "When some things cannot be told apart",
      idea: "Repeated letters, or seats round a table with no first seat, mean some arrangements are really the same one. Count them all, then divide the duplicates out.",
      concepts: ["restrictions-and-rules"],
      templates: ["countWordRepeatedLetters", "countCircular"] },
    { id: "count-tree", topic: "Counting Principle", title: "Three or more stages",
      idea: "The same rule carries on for as many stages as there are: multiply every stage together. A tree diagram is a way of seeing it, not a different method.",
      concepts: ["tree-diagrams"],
      templates: ["countTree"] },
    { id: "count-arrangements", warmUp: "count-stages", topic: "Counting Principle", title: "Arrangements without repeats",
      idea: "When nothing may be used twice, the pool shrinks by one at every stage: 5 choices, then 4, then 3. Order matters, so ABC and CBA count separately.",
      concepts: ["restrictions-and-rules"],
      templates: ["countArrangements"] },
    { id: "count-worded", warmUp: "count-stages", topic: "Counting Principle", title: "Counting with a rule attached",
      idea: "A rule such as 'must be even' or 'cannot start with 0' fixes one position first. Deal with the restricted position before counting the free ones.",
      concepts: ["worded-counting-problems"],
      templates: ["countWorded"] }
  ];

})();
